# ==============================================================================
# OpenSTA Configuration File: Pre-CTS Timing Analysis
# Tool: OpenSTA
# ==============================================================================

# Read technology libraries (Liberty format)
set_cmd_units -time ns -capacitance pF -current mA -voltage V -resistance kOhm -distance um
read_liberty -min /OpenLane/designs/picorv32a/src/sky130_fd_sc_hd__fast.lib
read_liberty -max /OpenLane/designs/picorv32a/src/sky130_fd_sc_hd__slow.lib

# Read synthesized gate-level Verilog netlist
read_verilog /OpenLane/designs/picorv32a/runs/RUN_2026.03.24_15.13.57/results/synthesis/picorv32a.synthesis.v

# Link design to the standard cell libraries
link_design picorv32a

# Read custom Synopsys Design Constraints (SDC)
read_sdc /OpenLane/designs/picorv32a/src/my_base.sdc

# Report checks for worst setup and hold paths
report_checks -path_delay min_max -fields {slew trans net cap input_pins} -format full_clock_expanded -digits 4

# Report worst negative slack (WNS) and total negative slack (TNS)
report_wns
report_tns
